spring:
  application:
    name: catalog-service
  config:
    import: "optional:configserver:"
  cloud:
    config:
      uri: http://localhost:8888
      request-connect-timeout: 5000
      request-read-timeout: 5000
      fail-fast: true
      retry:
        max-attempts: 6
        initial-interval: 1000
        max-interval: 2000
        multiplier: 1.1
  docker:
    compose:
      enabled: true
      file: docker-compose.yml
  datasource:
    username: user
    password: password
    url: jdbc:postgresql://localhost:5432/polardb_catalog
    hikari:
      connection-timeout: 2000
      maximum-pool-size: 5
  lifecycle:
    timeout-per-shutdown-phase: 15s
#  sql:
#    init:
#      mode: always
polar:
  greeting: "Hello, Polar!"
management:
  endpoints:
    web:
      exposure:
        include: refresh
server:
  shutdown: graceful