apiVersion: apps/v1
kind: Deployment
metadata:
  name: edge-service
  labels:
    app: edge-service
spec:
  replicas: 1
  selector:
    matchLabels:
      app: edge-service
  template:
    metadata:
      labels:
        app: edge-service
    spec:
      containers:
        - name: edge-service
          image: edge-service:0.0.1-SNAPSHOT
          imagePullPolicy: Never
          ports:
            - containerPort: 8081
          env:
            - name: CATALOG_SERVICE_URL
              value: http://catalog-service
            - name: SPRING_CLOUD_CONFIG_URI
              value: http://config-server:8888
            - name: ORDER_SERVICE_URI
              value: http://order-service
            - name: SPRING_DATA_REDIS_HOST
              value: polar-redis

          lifecycle:
            preStop:
              exec:
                command: [ "/bin/sh", "-c", "sleep 5" ]