version: '3.9'
services:
  catalog-service:
    depends_on:
      - polar-postgres
      - polar-redis
    image: "catalog-service"
    container_name: "catalog-service"
    ports:
      - "8080:8080"
    environment:
      - BPL_JVM_THREAD_COUNT=50
      - BPL_DEBUG_ENABLED=true
      - BPL_DEBUG_PORT=8001
      - SPRING_DATASOURCE_URL=jdbc:postgresql://polar-postgres:5432/polardb_catalog
      - SPRING_PROFILES_ACTIVE=test-data
      - SPRING_CLOUD_CONFIG_URI=http://config-server:8888
      - SPRING_DOCKER_COMPOSE_ENABLED=false
  config-server:
    image: "config-server:0.0.1-SNAPSHOT"
    container_name: "config-server"
    ports:
      - "8888:8888"
      - "9888:9888"
    environment:
      - BPL_JVM_THREAD_COUNT=50
      - BPL_DEBUG_ENABLED=true
      - BPL_DEBUG_PORT=8001
  polar-postgres:
    image: "postgres:16"
    container_name: "polar-postgres"
    ports:
      - "5432:5432"
    volumes:
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql
    environment:
      - POSTGRES_USER=user
      - POSTGRES_PASSWORD=password
      - POSTGRES_DB=polardb_catalog
  polar-redis:
    image: "redis:7.0"
    container_name: "polar-redis"
    ports:
      - "6379:6379"
  polar-rabbitmq:
    image: "rabbitmq:3.10-management"
    container_name: "polar-rabbitmq"
    ports:
      - "5672:5672"
      - "15672:15672"
    volumes:
      - ./rabbitmq/rabbitmq.conf:/etc/rabbitmq/rabbitmq.conf